{
 "title": "Mastodon",
 "description": "Dashboard for monitoring a Mastodon instance",
 "tags": [
  "mastodon",
  "system metrics",
  "redis",
  "postgres",
  "sidekiq"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis\")\n|> keyValues(keyColumns: [\"host\"])\n|> group()\n|> keep(columns: [\"_value\"])"
   },
   { "name": "mastodon_domain", "query": "mastodon.bentasker.co.uk" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TLS Certificate Remaining Validity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"x509_cert\")\n|> filter(fn: (r) => r._field == \"expiry\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> filter(fn: (r) => r.common_name == \"${mastodon_domain}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"server\", \"common_name\"])\n|> aggregateWindow(every: v.windowPeriod, fn: max)\n|> last()\n"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Depth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_default_queue_len\" or\n                    r._field == \"sidekiq_ingress_queue_len\" or\n                    r._field == \"sidekiq_mailers_queue_len\" or\n                    r._field == \"sidekiq_pull_queue_len\" or\n                    r._field == \"sidekiq_push_queue_len\" or\n                    r._field == \"sidekiq_scheduler_queue_len\"                 \n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> last()\n|> group()\n|> reduce(fn: (r, accumulator) => ({sum: r._value + accumulator.sum}), \n                                    identity: {sum: 0})\n\n\n\n"
    }
   ]
  },
  {
   "title": "Sidekiq Messages Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_stat_processed\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> last() \n\n"
    }
   ]
  },
  {
   "title": "Sidekiq Messages Errored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_stat_failed\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> last() \n\n"
    }
   ]
  },
  {
   "title": "Redis Hit Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"keyspace_hitrate\")          \n  |> filter(fn: (r) => r.host == \"${host}\")\n  //|> keep(columns: [\"_time\", \"_field\", \"_value\", \"replication_role\"])\n  |> last()\n                  "
    }
   ]
  },
  {
   "title": "HTTP Probe Result",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"http_response\")\n|> filter(fn: (r) => r._field == \"response_status_code_match\")\n|> filter(fn: (r) => r.host == \"${host}\")\n\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"server\"])\n|> aggregateWindow(every: v.windowPeriod, fn: min)\n"
    }
   ]
  },
  {
   "title": "SSL Certificate Check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"x509_cert\")\n|> filter(fn: (r) => r._field == \"verification_code\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> filter(fn: (r) => r.common_name == \"${mastodon_domain}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"server\"])\n|> aggregateWindow(every: v.windowPeriod, fn: max)\n// The HTTP checks use 1 for OK, and 0 for failure\n// x509 is the inverse\n// to keep the graphs consistent, invert this result\n|> map(fn: (r) => ({r with _value: 1 - r._value}))\n"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_default_queue_len\" or\n                    r._field == \"sidekiq_ingress_queue_len\" or\n                    r._field == \"sidekiq_mailers_queue_len\" or\n                    r._field == \"sidekiq_pull_queue_len\" or\n                    r._field == \"sidekiq_push_queue_len\" or\n                    r._field == \"sidekiq_scheduler_queue_len\"                 \n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> aggregateWindow(every: v.windowPeriod, fn: max)\n"
    }
   ]
  },
  {
   "title": "Sidekiq Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_stat_processed\" or\n                    r._field == \"sidekiq_stat_failed\"\n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> difference(nonNegative: true) \n|> aggregateWindow(every: v.windowPeriod, fn: max)\n"
    }
   ]
  },
  {
   "title": "Container Healthcheck Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"docker_container_health\")\n|> filter(fn: (r) => r._field == \"failing_streak\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> filter(fn: (r) => r.container_name == \"postgres\" or\n                     r.container_name == \"redis\" or\n                     r.container_name == \"sidekiq\" or\n                     r.container_name == \"streaming\" or \n                     r.container_name == \"web\"\n)\n\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"container_name\"])\n|> aggregateWindow(every: v.windowPeriod, fn: max)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_cpu\")\n  |> filter(fn: (r) => r._field == \"usage_percent\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.container_name == \"postgres\" or\n                     r.container_name == \"redis\" or\n                     r.container_name == \"sidekiq\" or\n                     r.container_name == \"streaming\" or \n                     r.container_name == \"web\"\n  )\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"container_name\"])\n  |> derivative(nonNegative: true, unit: 1s)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  // Convert bytes to bits\n  |> map(fn: (r) => ({r with _value: r._value * 8.0}))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_mem\")\n  |> filter(fn: (r) => r._field == \"usage\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.container_name == \"postgres\" or\n                     r.container_name == \"redis\" or\n                     r.container_name == \"sidekiq\" or\n                     r.container_name == \"streaming\" or \n                     r.container_name == \"web\"\n  )\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"container_name\"])\n  |> derivative(nonNegative: true, unit: 1s)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  // Convert bytes to bits\n  |> map(fn: (r) => ({r with _value: r._value * 8.0}))"
    }
   ]
  },
  {
   "title": "User Facing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_net\")\n  |> filter(fn: (r) => r._field == \"tx_bytes\" or\n                       r._field == \"rx_bytes\"\n  )\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.container_name == \"web\" or\n                     r.container_name == \"streaming\"\n  )\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"container_name\"])\n  |> derivative(nonNegative: true, unit: 1s)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  // Convert bytes to bits\n  |> map(fn: (r) => ({r with _value: r._value * 8.0}))"
    }
   ]
  },
  {
   "title": "Sidekiq Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"docker_container_net\")\n  |> filter(fn: (r) => r._field == \"tx_bytes\" or\n                       r._field == \"rx_bytes\"\n  )\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.container_name == \"sidekiq\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"container_name\"])\n  |> derivative(nonNegative: true, unit: 1s)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  // Convert bytes to bits\n  |> map(fn: (r) => ({r with _value: r._value * 8.0}))"
    }
   ]
  },
  {
   "title": "Postgres Aborted Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"sessions_abandoned\" or\n                       r._field == \"sessions_fatal\" or \n                       r._field == \"sessions_killed\"\n  )\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n\n\n"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tuples Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"tup_fetched\" or\n                       r._field == \"tup_returned\" \n\n  )\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Tuples Inserted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"tup_inserted\"\n  )\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Tuples Updated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"tup_updated\"\n  )\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Tuples Deleted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"tup_deleted\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Disk: Blocks Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"blks_read\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Disk: Block Cache Hit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"blks_hit\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Aborted Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"sessions_abandoned\" or\n                       r._field == \"sessions_fatal\" or \n                       r._field == \"sessions_killed\"\n  )\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n\n\n"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"deadlocks\"\n  )\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n\n\n"
      }
     ]
    },
    {
     "title": "Conflicts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"postgresql\")\n  |> filter(fn: (r) => r._field == \"conflicts\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r.db == \"mastodon\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"db\", \"server\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"uptime\")          \n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> last()\n                  "
      }
     ]
    },
    {
     "title": "Dataset Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"used_memory_dataset\")          \n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> last()\n                  "
      }
     ]
    },
    {
     "title": "Commands Processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"instantaneous_ops_per_sec\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"replication_role\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n                  "
      }
     ]
    },
    {
     "title": "Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"keyspace_hitrate\")          \n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"replication_role\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n                  "
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"clients\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"replication_role\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n                  "
      }
     ]
    },
    {
     "title": "New Connction Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"total_connections_received\" or \n                       r._field == \"rejected_connections\"\n                       )            \n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"replication_role\"])\n  |> derivative(unit: 1s, nonNegative: true) \n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n                  "
      }
     ]
    },
    {
     "title": "Evicted/Expired",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"evicted_keys\" or r._field == \"expired_keys\")        \n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"replication_role\"])\n  |> difference()\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\n                  "
      }
     ]
    }
   ]
  },
  {
   "title": "Sidekiq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidekiq Queue Depth",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_default_queue_len\" or\n                    r._field == \"sidekiq_ingress_queue_len\" or\n                    r._field == \"sidekiq_mailers_queue_len\" or\n                    r._field == \"sidekiq_pull_queue_len\" or\n                    r._field == \"sidekiq_push_queue_len\" or\n                    r._field == \"sidekiq_scheduler_queue_len\"                 \n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> last()\n|> group()\n|> reduce(fn: (r, accumulator) => ({sum: r._value + accumulator.sum}), \n                                    identity: {sum: 0})\n\n\n\n"
      }
     ]
    },
    {
     "title": "Retries",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_retries\")\n|> filter(fn: (r) => r.host == \"${host}\") \n|> last()\n"
      }
     ]
    },
    {
     "title": "Scheduled",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_scheduled\")\n|> filter(fn: (r) => r.host == \"${host}\") \n|> last()\n"
      }
     ]
    },
    {
     "title": "Dead",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_dead\")\n|> filter(fn: (r) => r.host == \"${host}\") \n|> last()\n"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_processes\")\n|> filter(fn: (r) => r.host == \"${host}\") \n|> last()\n"
      }
     ]
    },
    {
     "title": "Sidekiq Messages Processed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_stat_processed\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> last() \n\n"
      }
     ]
    },
    {
     "title": "Sidekiq Messages Errored",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_stat_failed\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> last() \n\n"
      }
     ]
    },
    {
     "title": "Sidekiq Error Rate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_stat_failed\" or\n                     r._field == \"sidekiq_stat_processed\"\n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> last() \n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> map(fn: (r) => ({\n     _value: float(v: r.sidekiq_stat_failed) / float(v :r.sidekiq_stat_failed + \n                                                  r.sidekiq_stat_processed)\n                                                  }))\n\n\n\n\n\n\n"
      }
     ]
    },
    {
     "title": "Sidekiq Queue Depth",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_default_queue_len\" or\n                    r._field == \"sidekiq_ingress_queue_len\" or\n                    r._field == \"sidekiq_mailers_queue_len\" or\n                    r._field == \"sidekiq_pull_queue_len\" or\n                    r._field == \"sidekiq_push_queue_len\" or\n                    r._field == \"sidekiq_scheduler_queue_len\"                 \n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Message Queue Processed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_stat_processed\" or\n                    r._field == \"sidekiq_stat_failed\"\n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> difference(nonNegative: true) \n|> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Message Queue Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "m/s" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_stat_processed\" or\n                    r._field == \"sidekiq_stat_failed\"\n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> derivative(nonNegative: true) \n|> aggregateWindow(every: v.windowPeriod, fn: max)\n"
      }
     ]
    },
    {
     "title": "Queue Depths",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"redis_commands\")\n|> filter(fn: (r) => r._field == \"sidekiq_default_queue_len\" or\n                    r._field == \"sidekiq_ingress_queue_len\" or\n                    r._field == \"sidekiq_mailers_queue_len\" or\n                    r._field == \"sidekiq_pull_queue_len\" or\n                    r._field == \"sidekiq_push_queue_len\" or\n                    r._field == \"sidekiq_scheduler_queue_len\"                 \n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "SSL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSL Certificate Check",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"x509_cert\")\n|> filter(fn: (r) => r._field == \"verification_code\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"server\", \"common_name\"])\n|> aggregateWindow(every: v.windowPeriod, fn: max)\n// The HTTP checks use 1 for OK, and 0 for failure\n// x509 is the inverse\n// to keep the graphs consistent, invert this result\n|> map(fn: (r) => ({r with _value: 1 - r._value}))\n"
      }
     ]
    },
    {
     "title": "TLS Certificate Remaining Validity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"x509_cert\")\n|> filter(fn: (r) => r._field == \"expiry\")\n|> filter(fn: (r) => r.host == \"${host}\")\n|> filter(fn: (r) => r.common_name == \"${mastodon_domain}\")\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"server\", \"common_name\"])\n|> aggregateWindow(every: v.windowPeriod, fn: max)\n\n"
      }
     ]
    },
    {
     "title": "SSL Certificate Check Failures",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "query": "from(bucket: \"telegraf\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"x509_cert\")\n|> filter(fn: (r) => r._field == \"verification_code\" or\n                     r._field == \"verification_error\"\n)\n|> filter(fn: (r) => r.host == \"${host}\")\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> filter(fn: (r) => r.verification_code == 1)\n|> keep(columns: [\"_time\", \"common_name\", \"verification_code\", \"verification_error\"])\n|> group()\n|> sort(columns: [\"_time\"], desc:true)\n"
      }
     ]
    }
   ]
  }
 ]
}